# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '29 16 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Deployment will be cancelled. Thank you for your contributions.'
          days-before-stale: 3
          days-before-close: 7
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned'
          operations-per-run: 1000
          remove-stale-when-updated: true
          only-labels: 'stale'
          close-pr-message: 'This pull request has been automatically closed because it has not had recent activity. Deployment will be cancelled. Reopen if this was mistake.'
          close-pr-label: 'closed'
